include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    comment_references: false
    avoid_print: false
analyzer:
  exclude:
    - lib/**.g.dart
  errors:
    # false positive when using Freezed
    invalid_annotation_target: ignore
