targets:
  $default:
    builders:
      freezed:
        options:
          union_key: type
          union_value_case: snake
          explicit_to_json: true
      json_serializable:
        options:
          field_rename: snake
global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
