name: yookassa_client
description: This package allows implementing payment acceptance into mobile, web, desktop apps and works as an extension to the YooMoney API
version: 1.0.3

repository: https://github.com/glin94/yookassa-dart-client
issue_tracker: https://github.com/glin94/yookassa-dart-client/issues
homepage: https://github.com/glin94/yookassa-dart-client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  stack_trace: ^1.11.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5
  test: ^1.24.9
  very_good_analysis: ^7.0.0
