name: yookassa_client
description: A Dart client for Yookassa Payments APIs, simplifying payment integration and transaction processing for web,desktop and mobile applications.

version: 1.0.5

homepage: https://github.com/glin94/yookassa-dart-client

repository: https://github.com/glin94/yookassa-dart-client

issue_tracker: https://github.com/glin94/yookassa-dart-client/issues

topics:
  - payments
  - yookassa

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  stack_trace: ^1.11.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5
  test: ^1.24.9
  very_good_analysis: ^7.0.0
